I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 400, in script
    jump day3cont1
ScriptError: could not find label 'day3cont1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 400, in script
    jump day3cont1
  File "C:\Users\Agnes\Desktop\renpy-7.3.2-sdk\renpy-7.3.2-sdk\renpy\ast.py", line 1695, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\Agnes\Desktop\renpy-7.3.2-sdk\renpy-7.3.2-sdk\renpy\script.py", line 894, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'day3cont1'.

Windows-8-6.2.9200
Ren'Py 7.3.2.320
Mood calls 1.0
Sun Jul 28 15:45:15 2019
